### ISSUE TITLE
Getting started with QmlVlcDemo

### ISSUE THREAD

**Issue by kevkha** [RSATom/QmlVlc#32]
Thanks for sharing your project. Could you please document in the readme how to get the demo working? I did a pull (or download the zip file) but both folders (libvlc-sdk and QmlVlc) in deps dir are empty. I follow the links from your demo on gitHub and able to download the missing dirs and sub dirs in question but when run/build the project there are many errors such as "file not found" (I changed from #include QmlVlc.h to #include QmlVlc/QmlVlc.h (note I removed the < and > for visibility here)) and many others for libvlc-sdk/include/vlc/ and I corrected them but not sure if I did the right thing. Now, I stuck at main.cpp:34: error: undefined reference to `RegisterQmlVlc()' and 6 more errors in the same main.cpp. I would like run the demo on both Windows and Ubuntu. Thanks in advance.

**Comment by RSATom** [comment]
You are right, It worth add some docs here. What platform do you want start first? - I will give you instructions how to build it.

**Comment by kevkha** [comment]
Thanks for your speedy response. I usually do my coding on Windows and copy the project to Ubuntu and run again to ensure everything is working so I guess Windows first, but the final program will be run on Ubuntu. Thanks.

**Comment by RSATom** [comment]
Ok, I'll try to do build instructions right now.
btw, some hints about building on Ubuntu already exists: https://github.com/RSATom/QmlVlcDemo/wiki/Build-hints

**Comment by kevkha** [comment]
Thanks. I am going to check the Ubuntu now and will check back on the Windows instructions once you have it posted. Thanks again for your works and time.

**Comment by RSATom** [comment]
btw, downloading sources archive will not work since there are submodules used. So you have to use git even on Windows:
 <code>git clone --recursive https://github.com/RSATom/QmlVlcDemo.git</code>

**Comment by RSATom** [comment]
I've added some hints for windows build. Check it please. If something is not clear - write please, I'll try to explain better.

**Comment by kevkha** [comment]
I have the use git bash for --recursive option to work (git GUI doesn't understand --recursive option on Windows). That did the trick for the clone part. I will try to build on Windows and see how it goes. Thanks.

**Comment by kevkha** [comment]
The build completed with several warnings as shown.
![image](https://cloud.githubusercontent.com/assets/1807308/6768026/1dfb0550-d021-11e4-9626-cc9b2a99e818.png)

Attempted to run the demo and it crashed

Starting C:\Users\Kevin\Documents\QtProjects\build-QmlVlcDemo-Desktop_Qt_5_4_0_MinGW_32bit-Debug\debug\QmlVlcDemo.exe...
The program has unexpectedly finished.
C:\Users\Kevin\Documents\QtProjects\build-QmlVlcDemo-Desktop_Qt_5_4_0_MinGW_32bit-Debug\debug\QmlVlcDemo.exe crashed

**Comment by RSATom** [comment]
This warnings is ok - I got the same all time.

About crash: try remove  `%VLC%\plugins\gui\libqt4_plugin.dll`

**Comment by kevkha** [comment]
Unfortunately, that did not help. I also moved libskins2_plugin.dll of out place, did a "Clean" and rebuild but same crash. How do we trace this crash? Currently, Qt is run in debug mode but I don't see any log in debug dir.

**Comment by RSATom** [comment]
what vlc version do you use?

**Comment by kevkha** [comment]
VLC 2.1.5

**Comment by RSATom** [comment]
can you see call stack in QtCreator?

**Comment by kevkha** [comment]
I click on "Start Debuging F5" button and see this "During startup program exited with code 0xc0000135." Does this help?

**Comment by RSATom** [comment]
0xc0000135 - is "Unable to locate Dll" exception. Do you have libvlc in %PATH% variable?

**Comment by kevkha** [comment]
I removed VLC 2.1.5 (64-bit) and installed VLC 2.2.0 (32-bit). Which libvlc are you referring to? I added C:\Program Files (x86)\VideoLAN\VLC to PATH but the same crash. I tried without libqt4_plugin.dll too. Still no go.

**Comment by RSATom** [comment]
Did you restart QtCreator after that?

**Comment by kevkha** [comment]
That's it. It worked my friend. I think we should document VLC to PATH too. By default VLC does not do it for us.
![image](https://cloud.githubusercontent.com/assets/1807308/6768172/0b5eb6e0-d02a-11e4-8b6a-7c4fea9a07b3.png)

And I confirm with libqt4_plugin.dll in place is ok too so main issue was VLC path for the libvlc.dll and others. Thanks so so much!

**Comment by RSATom** [comment]
Great!

> I think we should document VLC to PATH too. By default VLC does not do it for us.
Good point.
