### ISSUE TITLE
vlcPlayer.length for remote video does not work

### ISSUE THREAD

**Issue by kevkha** [RSATom/QmlVlc#35]
I have a JS script junction getTime() to convert "length" to M:S
This JsLogic.getTime(vlcPlayer.length) works for local video but not the remote video in the demo.

**Comment by RSATom** [comment]
It's well known libvlc issue. And this true for not all sources. All I can offer - use newer version of Vlc (maybe nightly build) in hope it fixed.

**Comment by kevkha** [comment]
Thanks. I observe the same with the latest VLC Player v2.2.0 for Windows.
