### ISSUE TITLE
VOB with two audio tracks

### ISSUE THREAD

**Issue by kevkha** [RSATom/QmlVlc#36]
My VOB karaoke video has two audio tracks as shown. VlcAudio.track and VlcAudio.channel does not seem to be for this feature. Am I right? I would like to toggle Track 1 and Track 2.

![image](https://cloud.githubusercontent.com/assets/1807308/6840880/c04c612a-d34e-11e4-863c-7e4423660c48.png)

**Comment by RSATom** [comment]
https://github.com/RSATom/WebChimera/wiki/QML-API#vlcaudio

`VlcAudio.channel ` is intended for switching between mono, stereo etc. modes
`VlcAudio.track` is exactly for switching audio tracks. 

What value do you get with `vlcPlayer.audio.count` when you file is playing?

**Comment by kevkha** [comment]
<code>vlcPlayer.audio.count</code> returns 3 which is right.
I attempted to change to track 2 like so <code>VlcAudio.track = 2</code> but it didn't work.
This one works, <code>vlcPlayer.audio.track = 2</code>

Thanks for leading me to the right direction!

**Comment by RSATom** [comment]
Yes `VlcAudio` is just type value of which `vlcPlayer.audio` returns. I.e. you can use `VlcAudio` directly only to access enum values (`VlcAdudio.Stereo` for example). In other cases you should get it via vlcPlayer property. Same valid for all other types mentioned in documentation.

**Comment by RSATom** [comment]
btw, when you used `VlcAudio.track = 2` you should got error in application output window in QtCreator.
