### ISSUE TITLE
multiple VlcPlayers & different volume values

### ISSUE THREAD

**Issue by pincopallopino** [RSATom/QmlVlc#38]
in my qml application i have two vlcplayers and i need to set different volume for each one. for example player1 -> muted and player2 -> volume: 50.. i tried it but when i set mute() on player1 also player2 got muted.. how can i do?

**Comment by kevkha** [comment]
I think like this vlcPlayer1.audio.mute and vlcPlayer2.audio.volume = 50. I assume you have two buttons for each player respectively. Try vlcPlayer.audio.toggleMute() for player1 and for player2 vlcPlayer2.audio.volume = 50

**Comment by RSATom** [comment]
@pincopallopino, do you use latest QmlVlc revision?

**Comment by RSATom** [comment]
I've tried

````
    Component.onCompleted: {
        vlcPlayer1.mute();
        vlcPlayer2.unMute();
    }
    Timer {
        interval: 3000; running: true; repeat: true
        onTriggered: { vlcPlayer1.toggleMute(); vlcPlayer1.toggleMute(); }
    }
````

and it works

**Comment by pincopallopino** [comment]
with your example, it not works (component.onCompleted).. i try this:

    Timer {
        interval: 3000;
        running: true;
        repeat: false;
        onTriggered: {
            vlcPlayer1.mute();
            vlcPlayer2.unMute();
        }
    }

and it works

**Comment by RSATom** [comment]
> with your example, it not works (component.onCompleted)...

Maybe because I've tested with debug build, it could introduce some differences.

If you problem is solved, please close this issue.
