### ISSUE TITLE
ошибка: library not found for -lvlc

### ISSUE THREAD

**Issue by rezedare** [RSATom/QmlVlc#43]
Здавствуйте! Пытаюсь собрать пример QmlVlcDemo с помощью Qt 5.4.0 на Mac OS X 10.9.5. Ничего не менялось в коде. VLC player установлен. При сборке возникает следующая проблема: library not found for -lvlc. Не подкажете, может что-то нужно доустановить?

**Comment by RSATom** [comment]
Честно говоря я давно уже не пробовал собирать QmlVlcDemo под Mac OS X, соответственно вполне возможно я что то сломал одним из последних изменений. Я проверю, спасибо.

**Comment by rezedare** [comment]
Спасибо за быстрый ответ. Буду ждать каких-нибудь новостей)

**Comment by RSATom** [comment]
Исправил - нужно было просто прописать путь для поиска libvlc.
В случае использования libvlc 2.2.x для успешного запуска нужно будет использовать libvlc из https://github.com/RSATom/WebChimera.js/releases/download/v.0.1.3/libvlc_2.2.1_mac.zip (т.к. в последних версиях libvlc есть ошибка связанная с поиском плагинов)

**Comment by rezedare** [comment]
Спасибо! Всё получилось. 

А видео формата rtsp Вы не пробовали воспроизводить?

**Comment by RSATom** [comment]
Вроде rtsp работал, но лучше проверить. Вообще библиотека должна успешно работать со всеми файлами которые воспроизводятся в VLC. Бывают конечно нюансы, но это редкость. Опять же, это еще может зависеть от используемой версии libvlc.
