### ISSUE TITLE
SHOUTcast links

### ISSUE THREAD

**Issue by aureyoboss** [RSATom/QmlVlc#44]
Hi,

I can't open a link like "http://yp.shoutcast.com/sbin/tunein-station.m3u?id=99189624" (from SHOUTcast API).
Yet with VideoLAN, it works very well.

You have an idea of the problem?

Thank you a lot.
Best regards.

**Comment by aureyoboss** [comment]
I found a solution:
Just do a "vlcPlayer.playlist.next()" one second after loading the link and it works...

**Comment by RSATom** [comment]
Sorry, I missed this issue.

**Comment by aureyoboss** [comment]
I have the same problem with CD Audio (compact disc digital audio).

**Comment by RSATom** [comment]
Did you try set `Normal` or `Loop` playback mode? http://wiki.webchimera.org/Plugin_QML_API#VlcPlaylist

By default it uses `Single` mode.

**Comment by aureyoboss** [comment]
Same result... :(

**Comment by RSATom** [comment]
Bug found. Will fix it withing hour or two.

**Comment by RSATom** [comment]
fixed

**Comment by aureyoboss** [comment]
How to use the playback mode ?
I trying "vlcPlayer.playlist.mode(Single)", "vlcPlayer.playlist.mode("Single")" or "vlcPlayer.playlist.mode = Single", without success...

**Comment by RSATom** [comment]
`vlcPlayer.playlist.mode = VlcPlaylist.Single`
