### ISSUE TITLE
Chapter object

### ISSUE THREAD

**Issue by aureyoboss** [RSATom/QmlVlc#45]
Do you have the ability to add the Chapter object :
- vlc.input.chapter.count
- vlc.input.chapter.track
- vlc.input.chapter.description
- vlc.input.chapter.countForTitle
- vlc.input.chapter.prev()
- vlc.input.chapter.next()

It would be great to read DVD video correctly.
Thanks.

**Comment by RSATom** [comment]
I'll look if it available in the libvlc API.

**Comment by RSATom** [comment]
It's available: https://github.com/RSATom/libvlc-sdk/blob/80fda1e853cac9e21de761141f6f0681373051ec/include/vlc/libvlc_media_player.h#L690

Ok, I'll add it when will have a bit of free time. Thanks!

**Comment by aureyoboss** [comment]
Any idea when it will be integrated ?
I want these for my project.

Many thanks.

**Comment by RSATom** [comment]
Unfortunately I'm a little bit limited with free time. Don't sure when could get some. Maybe next week, but can't promise.

**Comment by RSATom** [comment]
@ aureyoboss, please test it. And it will be great if you will add new properties/functions from to https://github.com/RSATom/QmlVlc/commit/68f950e018847831bb2de9f59e8727aa193cff03 the [API docs](https://github.com/RSATom/QmlVlc/wiki/QmlVlc-API)

**Comment by aureyoboss** [comment]
Hi RSATom,
I just did the first tests. For the moment:
- vlcPlayer.playlist.next();
- vlcPlayer.playlist.prev();
- vlcPlayer.input.chapter.description(i);

Return : TypeError: Property 'next' of object 0 is not a function

You have an idea ?
Thanks

**Comment by RSATom** [comment]
> vlcPlayer.playlist.next();
vlcPlayer.playlist.prev();

checked it works well for me.

> vlcPlayer.input.chapter.description(i);
vlcPlayer.input.title.description(i);

if you look to mentioned above patch, you will see I don't add separate `title` and `chapter` subobjects, but just added some new properties/function to the `input`

**Comment by aureyoboss** [comment]
Everything is ok, it works.
To edit the FAQ, there is no problem. But what is the edit mode (AsciiDoc, Creole...)?

**Comment by RSATom** [comment]
https://github.com/RSATom/QmlVlc/wiki/QmlVlc-API
It uses `MediaWiki` format

**Comment by aureyoboss** [comment]
Thanks. FAQ - Edition finished.

**Comment by RSATom** [comment]
@aureyoboss, thank you!
