### ISSUE TITLE
Playlist items object

### ISSUE THREAD

**Issue by aureyoboss** [RSATom/QmlVlc#46]
Hi RSATom,

Also, do you have the ability to add the Playlist items object :

- vlc.playlist.items.count
- vlc.playlist.items.clear()
- vlc.playlist.items.remove(number)

Many thanks.
Best regards

**Comment by RSATom** [comment]
it's already available: http://wiki.webchimera.org/Plugin_QML_API#VlcPlaylist

**Comment by RSATom** [comment]
please reopen issue if you think it's something wrong with already available API
