### ISSUE TITLE
Couldn't create libvlc instance. Check vlc plugins dir.

### ISSUE THREAD

**Issue by aratkevich** [RSATom/QmlVlc#50]
Собрал vlc (OSX), скопировал в /usr/local/lib при запуске QmlVlcDemo выдает сообщение Couldn't create libvlc instance. Check vlc plugins dir.
Не подскажите куда копать?

**Comment by RSATom** [comment]
В последней релизной версии `VLC` есть баг не поволяющий `libvlc` корректно работать вне `VLC.app`. Возможно это ваш случай. Для решения проблемы требуется использовать немного модифицированное дерево файлов из `VLC.app`. Взять его можно например здесь: https://github.com/RSATom/WebChimera.js/releases/download/v0.1.47/WebChimera.js_v0.1.47_nw_v0.12.3_VLC_v2.2.1_x64_osx.tar.gz

**Comment by aratkevich** [comment]
Да, помогло! Спасибо!

**Comment by RSATom** [comment]
Всегда пожалуйста.

**Comment by johnlu0907** [comment]
HI
Could you explain about the solution once again? what means ` using a slightly modified tree of files from VLC.app`?

**Comment by RSATom** [comment]
@johnlu0907 I had to add some symlinks to get it working. You can look example at https://github.com/RSATom/WebChimera.js/releases/download/v0.1.47/WebChimera.js_v0.1.47_nw_v0.12.3_VLC_v2.2.1_x64_osx.tar.gz

**Comment by RSATom** [comment]
and btw, I didn't check if it still works long time already... So some new issues are possible...

**Comment by johnlu0907** [comment]
I'm getting following issue:
```
Couldn't create libvlc instance. Check vlc plugins dir.
```
Have you had tested QmlVlc with libvlc 3.0.8?

**Comment by johnlu0907** [comment]
I'm developing streaming app using your libraries but I'm getting an issue as above.
Please help me asap.

**Comment by RSATom** [comment]
Yes, I've tried it with some libvlc 3.x but I did't try it with libvlc 3.x on Mac.

**Comment by johnlu0907** [comment]
I'm working on Ubuntu environment now.

**Comment by RSATom** [comment]
Do you have VLC installed?

**Comment by goplayegg** [comment]
> @johnlu0907 I had to add some symlinks to get it working. You can look example at https://github.com/RSATom/WebChimera.js/releases/download/v0.1.47/WebChimera.js_v0.1.47_nw_v0.12.3_VLC_v2.2.1_x64_osx.tar.gz

Thanks , I am experiencing this issue now, it works on vlc 3.0.12 Mac intel 64.
