### ISSUE TITLE
package management

### ISSUE THREAD

**Issue by Ivshti** [RSATom/QmlVlc#59]
Is there a de-facto standard for package management for C++ projects? IF there is, can we add QmlVlc to it?

**Comment by RSATom** [comment]
what do you mean by "package management"?

**Comment by RSATom** [comment]
if you mean something like npm for js - no there are no any package management systems for C/C++

**Comment by RSATom** [comment]
at least there are no really cross platform package management systems...

**Comment by Ivshti** [comment]
Yep, exactly what I was asking. If you are confident there's nothing we can do on the matter, let's close this
