### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by apitaud** [RSATom/QmlVlc#72]
Hi everybody, 
my question is a very beginner question. I can't  build QmlVlc with the cmake here. 
I did : 
 -> cd QmlVlc
 -> mkdir build
 -> cd build
 -> cmake ..
and an error occur : 
The source directory
/myPath/QmlVlc/libvlc_wrapper
does not contain a CMakeLists.txt file.

somebody can tell me how to build it ? 
thx a lot guys.

EDIT :
NVM guys, I just need to clone the libvlc_wrapper repo too

**Comment by RSATom** [comment]
yes, you should do `--recursive` clone, or `git submodules update --init --recursive` after clone.
