### ISSUE TITLE
Change Live555 stream transport settings

### ISSUE THREAD

**Issue by berkantay** [RSATom/QmlVlc#80]
My camera link is streaming via RTSP. Video plays succesfully for 1 min. however after about 1 minute display is freezing both on VLCPlayer itself and also on your QmlVlcDemo. When I change the ***Tools>Preferences>Input/Codecs>Network>Live555*** stream from http to rtsp Vlc player does not freeze. How can I set this from my code (QmlVlcDemo).

cheers

**Comment by berkantay** [comment]
```Sending request: OPTIONS rtsp://192.168.2.254/554 RTSP/1.0 CSeq: 6``` ``` User-Agent LibVLC/3.0.8 (LIVE5556 Streaming Media v2018.02.18)
Session 69855``` 


 I get this error and video stucks.

**Comment by RSATom** [comment]
I'll investigate it a little bit later.

**Comment by berkantay** [comment]
Thanks a lot !

**Comment by RSATom** [comment]
@berkantay you can try add
```
opts.push_back( "--rtsp-tcp" );
```
before https://github.com/RSATom/QmlVlc/blob/master/QmlVlcConfig.cpp#L182

**Comment by berkantay** [comment]
Thank you so much for your support! If you visit Turkey ***RAKI***s are on me!!! :DD
