### ISSUE TITLE
I'm getting an an issue on ubuntu 19.10

### ISSUE THREAD

**Issue by johnlu0907** [RSATom/QmlVlc#81]
QmlVlcDemo: ../QmlVlcDemo/deps/QmlVlc/QmlVlcVideoOutput.cpp:97: void QmlVlcVideoOutput::init(): Assertion `m_player && m_player->is_open()' failed.

**Comment by RSATom** [comment]
It's highly possible you just don't have libvlc plugins installed.

**Comment by johnlu0907** [comment]
I have installed vlc plugins base module. it is working for me now.
Thanks
