### ISSUE TITLE
Compiling on Windows environment

### ISSUE THREAD

**Issue by johnlu0907** [RSATom/QmlVlc#82]
I was built qmlvlc plugin on ubuntu environment by installing vlc-plugins. But I have not done on windows environment.
Please help me.

**Comment by RSATom** [comment]
One possible solution - Install VLC and add it to PATH environment variable

**Comment by johnlu0907** [comment]
I'm developing media player based libvlc and your wrapper module in Qt/Qml for windows. Without installation of vlc, do you have no another way?

**Comment by RSATom** [comment]
Just place .dlls from VLC near your executable

**Comment by johnlu0907** [comment]
thanks

**Comment by RSATom** [comment]
Looks like problem was solved
